package core

import "regexp"

const (
	DEFAULT_CONF_FILE_PATH = "build/conf/bb.yaml"

	LOCALDATE_FORMAT_LAYOUT = "2006-01-02"
	LOCALDATE_RE_LAYOUT     = `\d+-\d+-\d+`

	LOCALTIME_FORMAT_LAYOUT = "15:04:05"
	LOCALTIME_RE_LAYOUT     = `\d+:\d+:\d+`

	LOCALDATETIME_FORMAT_LAYOUT = "2006-01-02 15:04:05"
	LOCALDATETIME_RE_LAYOUT     = `\d+-\d+-\d+ \d+:\d+:\d+`

	LOCALDATETIME_MINUTE_FORMAT_LAYOUT = "2006-01-02 15:04"
	LOCALDATETIME_MINUTE_RE_LAYOUT     = `\d+-\d+-\d+ \d+:\d+`

	LOCALDATETIME_MILLSECOND_FORMAT_LAYOUT = "2006-01-02 15:04:05.000"
	LOCALDATETIME_MILLSECOND_RE_LAYOUT     = `\d+-\d+-\d+ \d+:\d+:\d+\.\d+`
)

var (
	LOCALDATETIME_RE            = regexp.MustCompile(LOCALDATETIME_RE_LAYOUT)
	LOCALDATETIME_MINUTE_RE     = regexp.MustCompile(LOCALDATETIME_MINUTE_RE_LAYOUT)
	LOCALDATETIME_MILLSECOND_RE = regexp.MustCompile(LOCALDATETIME_MILLSECOND_FORMAT_LAYOUT)
)
